# -*- coding: utf-8 -*-
"""doppler_shift

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AK_38_6AImq6rhc7UEeOEW9gVPiw31B_
"""

__all__ = ['doppler_shift']
def doppler_shift(rest, obs, velocity):
  """
  Function for calculating any one of the inputs based on the values for the other two. Input 'False' for
  the value you intend to find. Equation is more exact than dopplet_shift_approx_rest.

  Parameters:

  rest: Quantity
  The wavelength at rest, preferably in Angstroms. Must have the same units as obs.

  obs: Quantity
  The observed wavelength in your data, preferably in Angstroms. Must have the same units as rest.

  velocity: Quantity
  The heliocentric velocity of the object you are measuring, in km/sec.

  Returns:

  observed (if rest, velocity are False): Quantity
  rest_wave (if obs, velocity are False): Quantity
  vel (if rest, obs are False): Quantity

  """
  c = 299729

  if obs == False:
    observed = rest * ((1 + velocity / c)/(1 - velocity / c)) ** 0.5
    return observed

  elif rest == False:
    rest_wave = obs/(((1 + velocity / c)/(1 - velocity / c)) ** 0.5)
    return rest_wave

  elif velocity == False:
    vel = -c * ((obs / rest) ** 2 - 1)/((obs / rest) ** 2 + 1)
    return vel